### ISSUE TITLE
delay between loops

### ISSUE THREAD

**Issue by vmechele** [bradmartin/nativescript-audio#39]
Hi,

I'm playing a 5s mp3 file from a local repo on the player.
It is supposed to loop perfectly, however when playing it on the player, there is a blank.
(a moment between the loops where there is no sound playing)

How can I avoid this?

Thanks a lot!

Vincent

**Comment by bradmartin** [comment]
I'm planning to spend some time on the plugin soon - just busy lately. Not sure I've tested the loop much to give any good ideas. If you're using a small audio file - it might be better suited to use the nativescript-sound plugin. We used it in the WindChimes app https://github.com/NathanWalker/nativescript-ng2-windchimes and it worked great for playing sound files quickly. The audio player here is a bit more involved, so for a small audio file I would give this (https://github.com/jbristowe/nativescript-sound) a try. You can see the native code involved if you want to call the native apis directly also with your file and not use the plugin source since it's a bit dated and I don't know if John is maintaining it to be honest.

**Comment by vmechele** [comment]
Hey Brad,

Thanks for the suggestion. Tried it out but I can't loop that one so that's a problem too.
Unless  you know of a way to loop it? coz that would be a great fix. I just need a player that can loop a 5s soundfile & set the volume.
